# Generated by Django 5.0.14 on 2025-07-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('USD', 'Dólar'), ('EUR', 'Euro'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum')], max_length=3)),
                ('valor', models.DecimalField(decimal_places=8, max_digits=20)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
